### ISSUE TITLE
Remove origami-repo-data-client dependency

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami-codedocs#267]
The repo data client is used here to check if a component with the name and version that has been requested, before downloading it from github.

Seeing as the spec requires that origami components have a repo with the same name as the component, doing a request to github for a tarball at that name and version will tell us if it exists.

**Comment by JakeChampion** [comment]
To have this work correctly it will need to check all the GitHub organisations that are listed in the [Source Control section of the specification](https://origami.ft.com/spec/v1/components/#source-control) and use API Keys for each organisation which has the ability to view private repositories.
